use m2a_core::{
    AuroraMaterialSourceBindingV1, AuroraModelIrV1, AuroraModelNodeV1, AuroraModelSegmentV1,
    AuroraSegmentDeformationV1,
    placeable_collision::{
        PLACEABLE_PWK_NONWALK_SURFACE_ID_V1, inspect_ascii_placeable_walkmesh_v1,
        write_placeable_walkmesh_v1,
    },
};

fn translated_model() -> AuroraModelIrV1 {
    AuroraModelIrV1 {
        schema_version: 1,
        profile_id: "placeable-collision-test".to_owned(),
        source_sha256: "1".repeat(64),
        basis_status: "AURORA_Z_UP".to_owned(),
        engine_facing_proof: "OFFLINE_ONLY".to_owned(),
        uv_runtime_proof: "OFFLINE_ONLY".to_owned(),
        nodes: vec![
            AuroraModelNodeV1 {
                id: 0,
                name: "render_root".to_owned(),
                parent_id: None,
                bind_local_matrix: [
                    1.0, 0.0, 0.0, 0.0, //
                    0.0, 1.0, 0.0, 0.0, //
                    0.0, 0.0, 1.0, 0.0, //
                    0.0, 0.0, 0.0, 1.0,
                ],
            },
            AuroraModelNodeV1 {
                id: 1,
                name: "translated_mesh".to_owned(),
                parent_id: Some(0),
                bind_local_matrix: [
                    1.0, 0.0, 0.0, 0.0, //
                    0.0, 1.0, 0.0, 0.0, //
                    0.0, 0.0, 1.0, 0.0, //
                    1.0, 2.0, 0.0, 1.0,
                ],
            },
        ],
        material_source_bindings: vec![AuroraMaterialSourceBindingV1 {
            slot: 0,
            source_material_id: Some(0),
            source_material_name: Some("render".to_owned()),
        }],
        segments: vec![AuroraModelSegmentV1 {
            segment_id: 0,
            material_slot: 0,
            deformation: AuroraSegmentDeformationV1::Rigid,
            parent_node_id: 1,
            cast_shadow: true,
            positions: vec![
                [-0.5, -1.0, 0.0],
                [0.5, -1.0, 0.0],
                [-0.5, 1.0, 2.0],
                [0.5, 1.0, 2.0],
            ],
            normals: vec![[0.0, 0.0, 1.0]; 4],
            tangents: None,
            uv0: vec![[0.0, 0.0]; 4],
            indices: vec![0, 1, 2, 2, 1, 3],
            face_surface_ids: Vec::new(),
            weights: Vec::new(),
        }],
    }
}

#[test]
fn placeable_collision_derives_a_deterministic_ascii_nonwalk_xy_footprint() {
    let model = translated_model();
    let first = write_placeable_walkmesh_v1(&model, "m2a_collision").expect("write PWK");
    let second = write_placeable_walkmesh_v1(&model, "m2a_collision").expect("repeat PWK");

    assert_eq!(first.payload, second.payload);
    assert!(first.payload.is_ascii());
    assert!(!first.payload.contains(&0));
    assert!(
        first
            .payload
            .starts_with(b"# Generated by Meshy2Aurora\r\n")
    );
    assert!(first.payload.ends_with(b"endnode\r\n"));
    assert!(
        first
            .payload
            .split(|byte| *byte == b'\n')
            .all(|line| line.len() <= 255)
    );
    assert_eq!(first.report.model_resref, "m2a_collision");
    assert_eq!(first.report.root_node_name, "m2a_collision_pwk");
    assert_eq!(first.report.bounds_min, [0.5, 1.0]);
    assert_eq!(first.report.bounds_max, [1.5, 3.0]);
    assert_eq!(first.report.vertex_count, 4);
    assert_eq!(first.report.face_count, 2);
    assert_eq!(first.report.surface_id, PLACEABLE_PWK_NONWALK_SURFACE_ID_V1);
    assert_eq!(first.report.use_point_count, 0);

    assert_eq!(first.inspection.format, "nwn1-ascii-pwk");
    assert_eq!(first.inspection.mesh_nodes.len(), 1);
    assert!(first.inspection.use_points.is_empty());
    let mesh = &first.inspection.mesh_nodes[0];
    assert_eq!(mesh.node_name, "m2a_collision_wg");
    assert_eq!(mesh.parent_name, "m2a_collision_pwk");
    assert_eq!(mesh.vertices.len(), 4);
    assert_eq!(mesh.faces.len(), 2);
    assert_eq!(mesh.faces[0].vertex_indices, [2, 0, 3]);
    assert_eq!(mesh.faces[1].vertex_indices, [1, 3, 0]);
    assert_eq!(mesh.faces[0].adjacent_faces, [0, 0, 0]);
    assert_eq!(mesh.faces[1].adjacent_faces, [0, 0, 0]);
    assert!(
        mesh.faces
            .iter()
            .all(|face| face.surface_id == PLACEABLE_PWK_NONWALK_SURFACE_ID_V1)
    );
    assert!(
        mesh.vertices
            .iter()
            .all(|vertex| vertex[2].to_bits() == 0.0_f32.to_bits())
    );

    let text = std::str::from_utf8(&first.payload).expect("ASCII PWK");
    assert!(text.contains("node trimesh m2a_collision_wg\r\n"));
    assert!(text.contains("  parent m2a_collision_pwk\r\n"));
    assert!(text.contains("  verts 4\r\n"));
    assert!(text.contains("  faces 2\r\n"));
    assert!(text.contains("    2 0 3 1 0 0 0 7\r\n"));
    assert!(text.contains("    1 3 0 1 0 0 0 7\r\n"));

    let mut retail_style = b"#MAXDOOR ASCII\r\nfiledependancy example.max\r\n".to_vec();
    retail_style.extend_from_slice(&first.payload);
    inspect_ascii_placeable_walkmesh_v1(&retail_style)
        .expect("runtime-aligned reader accepts ignored retail top-level metadata");
}

#[test]
fn placeable_collision_rejects_nonfinite_or_degenerate_world_footprints() {
    let mut nonfinite = translated_model();
    nonfinite.nodes[1].bind_local_matrix[12] = f32::NAN;
    let error =
        write_placeable_walkmesh_v1(&nonfinite, "m2a_collision").expect_err("non-finite transform");
    assert_eq!(error.code, "PLACEABLE-PWK-TRANSFORM-INVALID");

    let mut degenerate = translated_model();
    for position in &mut degenerate.segments[0].positions {
        position[0] = 0.0;
    }
    let error =
        write_placeable_walkmesh_v1(&degenerate, "m2a_collision").expect_err("zero-width bounds");
    assert_eq!(error.code, "PLACEABLE-PWK-FOOTPRINT-DEGENERATE");
}

#[test]
fn ascii_placeable_walkmesh_reader_rejects_binary_payloads_and_overlong_lines() {
    let binary = [0, 0, 0, 0, 0x50, 0x04, 0, 0];
    let error =
        inspect_ascii_placeable_walkmesh_v1(&binary).expect_err("binary PWK must be rejected");
    assert_eq!(error.code, "PLACEABLE-PWK-BINARY-UNSUPPORTED");

    let mut overlong = vec![b'#'; 256];
    overlong.extend_from_slice(b"\r\n");
    let error = inspect_ascii_placeable_walkmesh_v1(&overlong)
        .expect_err("runtime line longer than 255 bytes must be rejected");
    assert_eq!(error.code, "PLACEABLE-PWK-LINE-TOO-LONG");
}

#[test]
fn ascii_placeable_walkmesh_reader_rejects_invalid_face_semantics() {
    let invalid = b"node trimesh invalid_wg\r\n\
  parent invalid_pwk\r\n\
  position 0 0 0\r\n\
  orientation 1 0 0 0\r\n\
  verts 3\r\n\
    0 0 0\r\n\
    1 0 0\r\n\
    0 1 0\r\n\
  faces 1\r\n\
    0 1 9 1 0 0 0 7\r\n\
endnode\r\n";
    let error = inspect_ascii_placeable_walkmesh_v1(invalid)
        .expect_err("out-of-range face vertex must be rejected");
    assert_eq!(error.code, "PLACEABLE-PWK-FACE-INDEX-INVALID");
}
