//! Deterministic production UTI writer and exact typed semantic readback.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::gff::{
    GFF_SCHEMA_VERSION, GffArtifactV1, GffDocumentV1, GffFieldV1, GffFileTypeV1, GffLimitsV1,
    GffLocStringV1, GffLocSubstringV1, GffStructV1, GffValueV1, GffWriterOptionsV1, read_gff_v32,
    write_gff_v32,
};
use crate::item::{
    ITEM_PROFILE_INVALID, ITEM_RECIPE_INVALID, ITEM_SCHEMA_INVALID, ITEM_SCHEMA_VERSION,
    ItemAppearanceRecipeV1, ItemColorRecipeV1, ItemCompositionProfileV1, ItemErrorV1,
    ItemIdentityV1, ItemPartSlotV1, required_item_part_slots_v1, sha256_hex,
    validate_item_recipe_v1,
};

pub const ITEM_UTI_INVALID: &str = "M2A-ITEM-UTI-INVALID";
pub const ITEM_UTI_FIELD_MISSING: &str = "M2A-ITEM-UTI-FIELD-MISSING";
pub const ITEM_UTI_FIELD_UNEXPECTED: &str = "M2A-ITEM-UTI-FIELD-UNEXPECTED";
pub const ITEM_UTI_FIELD_TYPE_INVALID: &str = "M2A-ITEM-UTI-FIELD-TYPE-INVALID";
pub const ITEM_UTI_SEMANTIC_DIFF: &str = "M2A-ITEM-UTI-SEMANTIC-DIFF";
pub const ITEM_PALETTE_INVALID: &str = "M2A-ITEM-PALETTE-INVALID";
pub const ITEM_PALETTE_ID_UNSUPPORTED: &str = "M2A-ITEM-PALETTE-ID-UNSUPPORTED";
pub const ITEM_PALETTE_SEMANTIC_DIFF: &str = "M2A-ITEM-PALETTE-SEMANTIC-DIFF";

pub const ITEM_PALETTE_RESOURCE_TYPE: u16 = 2030;
pub const ITEM_HELMET_PALETTE_ID: u8 = 9;

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ItemUtiPropertiesV1 {
    pub description: String,
    pub identified_description: String,
    pub charges: u8,
    pub cost: u32,
    pub add_cost: u32,
    pub stack_size: u16,
    pub stolen: bool,
    pub plot: bool,
    pub identified: bool,
    pub cursed: bool,
    pub palette_id: u8,
    pub comment: String,
}

impl Default for ItemUtiPropertiesV1 {
    fn default() -> Self {
        Self {
            description: String::new(),
            identified_description: String::new(),
            charges: 0,
            cost: 0,
            add_cost: 0,
            stack_size: 1,
            stolen: false,
            plot: false,
            identified: true,
            cursed: false,
            palette_id: 0,
            comment: "Generated by Meshy2Aurora item pipeline.".to_owned(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ItemUtiBuildRequestV1 {
    pub schema_version: u32,
    pub recipe: ItemAppearanceRecipeV1,
    pub properties: ItemUtiPropertiesV1,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ItemUtiPartV1 {
    pub slot: ItemPartSlotV1,
    pub variant: u8,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ItemUtiReadbackV1 {
    pub schema_version: u32,
    pub payload_sha256: String,
    pub identity: ItemIdentityV1,
    pub base_item: u32,
    pub profile: ItemCompositionProfileV1,
    pub parts: Vec<ItemUtiPartV1>,
    pub colors: Option<ItemColorRecipeV1>,
    pub properties: ItemUtiPropertiesV1,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ItemUtiWriteReportV1 {
    pub schema_version: u32,
    pub byte_length: u64,
    pub payload_sha256: String,
    pub field_count: u32,
    pub profile: ItemCompositionProfileV1,
    pub semantic_readback_status: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ItemUtiArtifactV1 {
    pub payload: Vec<u8>,
    pub report: ItemUtiWriteReportV1,
    pub readback: ItemUtiReadbackV1,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ItemPaletteEntryV1 {
    pub uti_resref: String,
    pub display_name: String,
    pub palette_id: u8,
}

/// Emits a minimal module-local `itempalcus.itp` for one helmet blueprint.
///
/// The independent tree uses the audited retail Item palette route
/// `Armor -> Helmets`, whose category ID is 9. The caller-owned NAME/RESREF
/// leaf is the only blueprint entry.
pub fn write_item_palette_itp_v1(entry: &ItemPaletteEntryV1) -> Result<GffArtifactV1, ItemErrorV1> {
    if entry.uti_resref.is_empty()
        || entry.uti_resref.len() > 16
        || !entry
            .uti_resref
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_')
    {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_INVALID,
            "entry.utiResref",
            "UTI ResRef must contain 1..16 lowercase ASCII letters, digits, or underscores",
        ));
    }
    if entry.display_name.is_empty()
        || entry.display_name.len() > 128
        || entry.display_name.chars().any(char::is_control)
    {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_INVALID,
            "entry.displayName",
            "display name must contain 1..128 UTF-8 bytes without control characters",
        ));
    }
    if entry.palette_id != ITEM_HELMET_PALETTE_ID {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_ID_UNSUPPORTED,
            "entry.paletteId",
            format!("helmet custom palette requires audited category ID {ITEM_HELMET_PALETTE_ID}"),
        ));
    }

    let leaf = GffStructV1 {
        struct_id: 0,
        fields: vec![
            field("NAME", string(&entry.display_name)),
            field("RESREF", GffValueV1::ResRef(entry.uti_resref.clone())),
        ],
    };
    let helmets = GffStructV1 {
        struct_id: 1,
        fields: vec![
            field("STRREF", GffValueV1::Dword(6739)),
            field("ID", GffValueV1::Byte(ITEM_HELMET_PALETTE_ID)),
            field("LIST", GffValueV1::List(vec![leaf])),
        ],
    };
    let armor = GffStructV1 {
        struct_id: 1,
        fields: vec![
            field("STRREF", GffValueV1::Dword(335)),
            field("TYPE", GffValueV1::Byte(2)),
            field("LIST", GffValueV1::List(vec![helmets])),
        ],
    };
    let document = GffDocumentV1 {
        schema_version: GFF_SCHEMA_VERSION,
        file_type: GffFileTypeV1::Itp,
        root: GffStructV1 {
            struct_id: u32::MAX,
            fields: vec![
                field("MAIN", GffValueV1::List(vec![armor])),
                field("NEXT_USEABLE_ID", GffValueV1::Byte(65)),
                field("RESTYPE", GffValueV1::Word(2025)),
            ],
        },
    };
    let artifact = write_gff_v32(&document, &GffWriterOptionsV1::default()).map_err(|error| {
        ItemErrorV1::fatal(
            ITEM_PALETTE_INVALID,
            "itempalcus.itp",
            format!("{}: {}", error.code, error.message),
        )
    })?;
    validate_item_palette_itp_readback(&artifact.payload, entry)?;
    Ok(artifact)
}

fn validate_item_palette_itp_readback(
    bytes: &[u8],
    expected: &ItemPaletteEntryV1,
) -> Result<(), ItemErrorV1> {
    let document = read_gff_v32(bytes, &GffLimitsV1::default()).map_err(|error| {
        ItemErrorV1::fatal(
            ITEM_PALETTE_INVALID,
            "itempalcus.itp",
            format!("palette readback failed: {error}"),
        )
    })?;
    if document.file_type != GffFileTypeV1::Itp || document.root.struct_id != u32::MAX {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_SEMANTIC_DIFF,
            "itempalcus.itp.header",
            "custom Item palette file type or root StructID differs",
        ));
    }
    let main = item_palette_list(&document.root, "MAIN", "itempalcus.itp.MAIN")?;
    if main.len() != 1 {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_SEMANTIC_DIFF,
            "itempalcus.itp.MAIN",
            "custom Item palette must contain exactly one Armor route",
        ));
    }
    let categories = item_palette_list(&main[0], "LIST", "itempalcus.itp.MAIN[0].LIST")?;
    if categories.len() != 1
        || item_palette_value(&categories[0], "ID")
            != Some(&GffValueV1::Byte(ITEM_HELMET_PALETTE_ID))
    {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_SEMANTIC_DIFF,
            "itempalcus.itp.helmets",
            "custom Item palette must contain exact Helmets category ID 9",
        ));
    }
    let entries = item_palette_list(&categories[0], "LIST", "itempalcus.itp.helmets.LIST")?;
    if entries.len() != 1
        || item_palette_value(&entries[0], "NAME") != Some(&string(&expected.display_name))
        || item_palette_value(&entries[0], "RESREF")
            != Some(&GffValueV1::ResRef(expected.uti_resref.clone()))
    {
        return Err(ItemErrorV1::fatal(
            ITEM_PALETTE_SEMANTIC_DIFF,
            "itempalcus.itp.helmets.LIST",
            "custom Item palette must contain exactly one matching NAME/RESREF leaf",
        ));
    }
    Ok(())
}

fn item_palette_value<'a>(structure: &'a GffStructV1, label: &str) -> Option<&'a GffValueV1> {
    structure
        .fields
        .iter()
        .find(|field| field.label == label)
        .map(|field| &field.value)
}

fn item_palette_list<'a>(
    structure: &'a GffStructV1,
    label: &str,
    path: &str,
) -> Result<&'a [GffStructV1], ItemErrorV1> {
    match item_palette_value(structure, label) {
        Some(GffValueV1::List(value)) => Ok(value),
        _ => Err(ItemErrorV1::fatal(
            ITEM_PALETTE_SEMANTIC_DIFF,
            path,
            "required palette list is missing or has the wrong type",
        )),
    }
}

pub fn write_item_uti_v1(
    request: &ItemUtiBuildRequestV1,
    options: &GffWriterOptionsV1,
) -> Result<ItemUtiArtifactV1, ItemErrorV1> {
    if request.schema_version != ITEM_SCHEMA_VERSION {
        return Err(ItemErrorV1::fatal(
            ITEM_SCHEMA_INVALID,
            "request.schemaVersion",
            format!("expected schema version {ITEM_SCHEMA_VERSION}"),
        ));
    }
    validate_item_recipe_v1(&request.recipe)?;
    validate_properties(&request.properties)?;
    let base_item = i32::try_from(request.recipe.base_item.physical_row_index).map_err(|_| {
        ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "request.recipe.baseItem.physicalRowIndex",
            "BaseItem does not fit the native GFF INT field",
        )
    })?;

    let mut fields = vec![
        field(
            "TemplateResRef",
            GffValueV1::ResRef(request.recipe.identity.uti_resref.clone()),
        ),
        field("BaseItem", GffValueV1::Int(base_item)),
        field(
            "LocalizedName",
            loc_string(&request.recipe.identity.display_name),
        ),
        field("Description", loc_string(&request.properties.description)),
        field(
            "DescIdentified",
            loc_string(&request.properties.identified_description),
        ),
        field("Tag", string(&request.recipe.identity.tag)),
        field("Charges", GffValueV1::Byte(request.properties.charges)),
        field("Cost", GffValueV1::Dword(request.properties.cost)),
        field("Stolen", boolean(request.properties.stolen)),
        field("StackSize", GffValueV1::Word(request.properties.stack_size)),
        field("Plot", boolean(request.properties.plot)),
        field("AddCost", GffValueV1::Dword(request.properties.add_cost)),
        field("Identified", boolean(request.properties.identified)),
        field("Cursed", boolean(request.properties.cursed)),
    ];
    for slot in required_item_part_slots_v1(request.recipe.base_item.profile) {
        let part = request
            .recipe
            .parts
            .iter()
            .find(|part| part.slot == *slot)
            .expect("validated recipe contains every required slot");
        fields.push(field(
            appearance_label(*slot, request.recipe.base_item.profile)?,
            GffValueV1::Byte(part.variant),
        ));
    }
    if let Some(colors) = request.recipe.colors {
        fields.extend(color_fields(colors));
    }
    fields.extend([
        field("PropertiesList", GffValueV1::List(Vec::new())),
        field("PaletteID", GffValueV1::Byte(request.properties.palette_id)),
        field("Comment", string(&request.properties.comment)),
    ]);

    let field_count = u32::try_from(fields.len()).expect("bounded Item UTI field count fits u32");
    let document = GffDocumentV1 {
        schema_version: GFF_SCHEMA_VERSION,
        file_type: GffFileTypeV1::Uti,
        root: GffStructV1 {
            struct_id: u32::MAX,
            fields,
        },
    };
    let artifact = write_gff_v32(&document, options).map_err(|error| {
        ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "uti",
            format!("{}: {}", error.code, error.message),
        )
    })?;
    let readback = read_item_uti_v1(
        &artifact.payload,
        request.recipe.base_item.profile,
        &options.limits,
    )?;
    let expected = expected_readback(request, &artifact.report.output_sha256);
    if readback != expected {
        return Err(ItemErrorV1::fatal(
            ITEM_UTI_SEMANTIC_DIFF,
            "uti.readback",
            "own readback differs from the requested typed UTI semantics",
        ));
    }
    Ok(ItemUtiArtifactV1 {
        payload: artifact.payload,
        report: ItemUtiWriteReportV1 {
            schema_version: ITEM_SCHEMA_VERSION,
            byte_length: artifact.report.byte_length,
            payload_sha256: artifact.report.output_sha256,
            field_count,
            profile: request.recipe.base_item.profile,
            semantic_readback_status: "PASS".to_owned(),
        },
        readback,
    })
}

pub fn read_item_uti_v1(
    bytes: &[u8],
    profile: ItemCompositionProfileV1,
    limits: &GffLimitsV1,
) -> Result<ItemUtiReadbackV1, ItemErrorV1> {
    let document = read_gff_v32(bytes, limits).map_err(|error| {
        ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "uti",
            format!("{}: {}", error.code, error.message),
        )
    })?;
    if document.file_type != GffFileTypeV1::Uti || document.root.struct_id != u32::MAX {
        return Err(ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "uti.root",
            "expected exact UTI V3.2 file type and root struct id 0xffffffff",
        ));
    }
    let fields: HashMap<&str, &GffValueV1> = document
        .root
        .fields
        .iter()
        .map(|field| (field.label.as_str(), &field.value))
        .collect();
    if fields.len() != document.root.fields.len() {
        return Err(ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "uti.root.fields",
            "duplicate UTI field labels are forbidden",
        ));
    }
    let expected_labels = expected_field_labels(profile)?;
    for field in &document.root.fields {
        if !expected_labels.contains(&field.label.as_str()) {
            return Err(ItemErrorV1::fatal(
                ITEM_UTI_FIELD_UNEXPECTED,
                format!("uti.{}", field.label),
                "field does not belong to the selected ModelType profile",
            ));
        }
    }
    for label in &expected_labels {
        if !fields.contains_key(label) {
            return Err(ItemErrorV1::fatal(
                ITEM_UTI_FIELD_MISSING,
                format!("uti.{label}"),
                "required typed UTI field is missing",
            ));
        }
    }
    if fields.len() != expected_labels.len() {
        return Err(ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            "uti.root.fields",
            "UTI field set does not exactly match the selected profile",
        ));
    }

    let template_resref = resref_value(&fields, "TemplateResRef")?;
    let base_item = int_value(&fields, "BaseItem")?;
    let base_item = u32::try_from(base_item).map_err(|_| {
        ItemErrorV1::fatal(
            ITEM_UTI_FIELD_TYPE_INVALID,
            "uti.BaseItem",
            "BaseItem must be a non-negative GFF INT",
        )
    })?;
    let identity = ItemIdentityV1 {
        uti_resref: template_resref,
        tag: string_value(&fields, "Tag")?,
        display_name: loc_string_value(&fields, "LocalizedName")?,
    };
    let mut parts = Vec::with_capacity(required_item_part_slots_v1(profile).len());
    for slot in required_item_part_slots_v1(profile) {
        let label = appearance_label(*slot, profile)?;
        parts.push(ItemUtiPartV1 {
            slot: *slot,
            variant: byte_value(&fields, label)?,
        });
    }
    let colors = matches!(
        profile,
        ItemCompositionProfileV1::ModelType1 | ItemCompositionProfileV1::ModelType3
    )
    .then(|| {
        Ok::<_, ItemErrorV1>(ItemColorRecipeV1 {
            leather1: byte_value(&fields, "Leather1Color")?,
            leather2: byte_value(&fields, "Leather2Color")?,
            cloth1: byte_value(&fields, "Cloth1Color")?,
            cloth2: byte_value(&fields, "Cloth2Color")?,
            metal1: byte_value(&fields, "Metal1Color")?,
            metal2: byte_value(&fields, "Metal2Color")?,
        })
    })
    .transpose()?;
    match required_field(&fields, "PropertiesList")? {
        GffValueV1::List(values) if values.is_empty() => {}
        GffValueV1::List(_) => {
            return Err(ItemErrorV1::fatal(
                ITEM_UTI_INVALID,
                "uti.PropertiesList",
                "ITEM-V1 supports only an empty PropertiesList",
            ));
        }
        _ => return Err(field_type_error("PropertiesList", "LIST")),
    }
    let properties = ItemUtiPropertiesV1 {
        description: loc_string_value(&fields, "Description")?,
        identified_description: loc_string_value(&fields, "DescIdentified")?,
        charges: byte_value(&fields, "Charges")?,
        cost: dword_value(&fields, "Cost")?,
        add_cost: dword_value(&fields, "AddCost")?,
        stack_size: word_value(&fields, "StackSize")?,
        stolen: bool_value(&fields, "Stolen")?,
        plot: bool_value(&fields, "Plot")?,
        identified: bool_value(&fields, "Identified")?,
        cursed: bool_value(&fields, "Cursed")?,
        palette_id: byte_value(&fields, "PaletteID")?,
        comment: string_value(&fields, "Comment")?,
    };
    validate_properties(&properties)?;

    Ok(ItemUtiReadbackV1 {
        schema_version: ITEM_SCHEMA_VERSION,
        payload_sha256: sha256_hex(bytes),
        identity,
        base_item,
        profile,
        parts,
        colors,
        properties,
    })
}

fn validate_properties(properties: &ItemUtiPropertiesV1) -> Result<(), ItemErrorV1> {
    if properties.stack_size == 0 {
        return Err(ItemErrorV1::fatal(
            ITEM_RECIPE_INVALID,
            "properties.stackSize",
            "stack size must be greater than zero",
        ));
    }
    for (path, value) in [
        ("properties.description", &properties.description),
        (
            "properties.identifiedDescription",
            &properties.identified_description,
        ),
        ("properties.comment", &properties.comment),
    ] {
        if value.len() > 65_535 {
            return Err(ItemErrorV1::fatal(
                ITEM_RECIPE_INVALID,
                path,
                "text exceeds the bounded Item UTI contract",
            ));
        }
    }
    Ok(())
}

fn expected_readback(request: &ItemUtiBuildRequestV1, hash: &str) -> ItemUtiReadbackV1 {
    ItemUtiReadbackV1 {
        schema_version: ITEM_SCHEMA_VERSION,
        payload_sha256: hash.to_owned(),
        identity: request.recipe.identity.clone(),
        base_item: request.recipe.base_item.physical_row_index,
        profile: request.recipe.base_item.profile,
        parts: required_item_part_slots_v1(request.recipe.base_item.profile)
            .iter()
            .map(|slot| {
                let part = request
                    .recipe
                    .parts
                    .iter()
                    .find(|part| part.slot == *slot)
                    .expect("validated recipe contains every required slot");
                ItemUtiPartV1 {
                    slot: *slot,
                    variant: part.variant,
                }
            })
            .collect(),
        colors: request.recipe.colors,
        properties: request.properties.clone(),
    }
}

fn expected_field_labels(
    profile: ItemCompositionProfileV1,
) -> Result<Vec<&'static str>, ItemErrorV1> {
    let mut labels = vec![
        "TemplateResRef",
        "BaseItem",
        "LocalizedName",
        "Description",
        "DescIdentified",
        "Tag",
        "Charges",
        "Cost",
        "Stolen",
        "StackSize",
        "Plot",
        "AddCost",
        "Identified",
        "Cursed",
    ];
    for slot in required_item_part_slots_v1(profile) {
        labels.push(appearance_label(*slot, profile)?);
    }
    if matches!(
        profile,
        ItemCompositionProfileV1::ModelType1 | ItemCompositionProfileV1::ModelType3
    ) {
        labels.extend([
            "Leather1Color",
            "Leather2Color",
            "Cloth1Color",
            "Cloth2Color",
            "Metal1Color",
            "Metal2Color",
        ]);
    }
    labels.extend(["PropertiesList", "PaletteID", "Comment"]);
    Ok(labels)
}

fn appearance_label(
    slot: ItemPartSlotV1,
    profile: ItemCompositionProfileV1,
) -> Result<&'static str, ItemErrorV1> {
    let label = match (profile, slot) {
        (
            ItemCompositionProfileV1::ModelType0 | ItemCompositionProfileV1::ModelType1,
            ItemPartSlotV1::Model,
        ) => "ModelPart1",
        (ItemCompositionProfileV1::ModelType2, ItemPartSlotV1::Bottom) => "ModelPart1",
        (ItemCompositionProfileV1::ModelType2, ItemPartSlotV1::Middle) => "ModelPart2",
        (ItemCompositionProfileV1::ModelType2, ItemPartSlotV1::Top) => "ModelPart3",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRFoot) => "ArmorPart_RFoot",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLFoot) => "ArmorPart_LFoot",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRShin) => "ArmorPart_RShin",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLShin) => "ArmorPart_LShin",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLThigh) => "ArmorPart_LThigh",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRThigh) => "ArmorPart_RThigh",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorPelvis) => "ArmorPart_Pelvis",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorTorso) => "ArmorPart_Torso",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorBelt) => "ArmorPart_Belt",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorNeck) => "ArmorPart_Neck",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRForearm) => "ArmorPart_RFArm",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLForearm) => "ArmorPart_LFArm",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRBicep) => "ArmorPart_RBicep",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLBicep) => "ArmorPart_LBicep",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRShoulder) => {
            "ArmorPart_RShoul"
        }
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLShoulder) => {
            "ArmorPart_LShoul"
        }
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRHand) => "ArmorPart_RHand",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorLHand) => "ArmorPart_LHand",
        (ItemCompositionProfileV1::ModelType3, ItemPartSlotV1::ArmorRobe) => "ArmorPart_Robe",
        _ => {
            return Err(ItemErrorV1::fatal(
                ITEM_PROFILE_INVALID,
                "uti.appearance",
                "part slot does not belong to the selected ModelType profile",
            ));
        }
    };
    Ok(label)
}

fn color_fields(colors: ItemColorRecipeV1) -> [GffFieldV1; 6] {
    [
        field("Leather1Color", GffValueV1::Byte(colors.leather1)),
        field("Leather2Color", GffValueV1::Byte(colors.leather2)),
        field("Cloth1Color", GffValueV1::Byte(colors.cloth1)),
        field("Cloth2Color", GffValueV1::Byte(colors.cloth2)),
        field("Metal1Color", GffValueV1::Byte(colors.metal1)),
        field("Metal2Color", GffValueV1::Byte(colors.metal2)),
    ]
}

fn field(label: &str, value: GffValueV1) -> GffFieldV1 {
    GffFieldV1 {
        label: label.to_owned(),
        value,
    }
}

fn string(value: &str) -> GffValueV1 {
    GffValueV1::String(value.as_bytes().to_vec())
}

fn loc_string(value: &str) -> GffValueV1 {
    GffValueV1::LocString(GffLocStringV1 {
        string_ref: u32::MAX,
        substrings: vec![GffLocSubstringV1 {
            string_id: 0,
            bytes: value.as_bytes().to_vec(),
        }],
    })
}

const fn boolean(value: bool) -> GffValueV1 {
    GffValueV1::Byte(value as u8)
}

fn required_field<'a>(
    fields: &'a HashMap<&str, &GffValueV1>,
    label: &str,
) -> Result<&'a GffValueV1, ItemErrorV1> {
    fields.get(label).copied().ok_or_else(|| {
        ItemErrorV1::fatal(
            ITEM_UTI_FIELD_MISSING,
            format!("uti.{label}"),
            "required typed UTI field is missing",
        )
    })
}

fn byte_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<u8, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::Byte(value) => Ok(*value),
        _ => Err(field_type_error(label, "BYTE")),
    }
}

fn bool_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<bool, ItemErrorV1> {
    match byte_value(fields, label)? {
        0 => Ok(false),
        1 => Ok(true),
        value => Err(ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            format!("uti.{label}"),
            format!("boolean BYTE must be 0 or 1, got {value}"),
        )),
    }
}

fn word_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<u16, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::Word(value) => Ok(*value),
        _ => Err(field_type_error(label, "WORD")),
    }
}

fn dword_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<u32, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::Dword(value) => Ok(*value),
        _ => Err(field_type_error(label, "DWORD")),
    }
}

fn int_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<i32, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::Int(value) => Ok(*value),
        _ => Err(field_type_error(label, "INT")),
    }
}

fn resref_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<String, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::ResRef(value) => Ok(value.clone()),
        _ => Err(field_type_error(label, "RESREF")),
    }
}

fn string_value(fields: &HashMap<&str, &GffValueV1>, label: &str) -> Result<String, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::String(value) => String::from_utf8(value.clone()).map_err(|_| {
            ItemErrorV1::fatal(
                ITEM_UTI_INVALID,
                format!("uti.{label}"),
                "CExoString must contain valid UTF-8",
            )
        }),
        _ => Err(field_type_error(label, "CEXOSTRING")),
    }
}

fn loc_string_value(
    fields: &HashMap<&str, &GffValueV1>,
    label: &str,
) -> Result<String, ItemErrorV1> {
    match required_field(fields, label)? {
        GffValueV1::LocString(value)
            if value.string_ref == u32::MAX
                && value.substrings.len() == 1
                && value.substrings[0].string_id == 0 =>
        {
            String::from_utf8(value.substrings[0].bytes.clone()).map_err(|_| {
                ItemErrorV1::fatal(
                    ITEM_UTI_INVALID,
                    format!("uti.{label}"),
                    "localized string must contain valid UTF-8",
                )
            })
        }
        GffValueV1::LocString(_) => Err(ItemErrorV1::fatal(
            ITEM_UTI_INVALID,
            format!("uti.{label}"),
            "localized string must use stringRef=-1 and exactly substring id 0",
        )),
        _ => Err(field_type_error(label, "CEXOLOCSTRING")),
    }
}

fn field_type_error(label: &str, expected: &str) -> ItemErrorV1 {
    ItemErrorV1::fatal(
        ITEM_UTI_FIELD_TYPE_INVALID,
        format!("uti.{label}"),
        format!("expected exact GFF {expected} field type"),
    )
}
