use std::{env, fs, io::Write, path::Path};

use m2a_core::{
    erf::{ErfArchive, ErfFileType},
    gff::{
        GffDocumentV1, GffFileTypeV1, GffLocStringV1, GffLocSubstringV1, GffStructV1, GffValueV1,
        GffWriterOptionsV1, read_gff_v32, write_gff_v32,
    },
    hak::{HakResourceInputV1, HakWriterOptionsV1, write_erf_archive_v1},
    item::ItemAppearanceRecipeV1,
    item_package::{
        GIC_RESOURCE_TYPE, GIT_RESOURCE_TYPE, IFO_RESOURCE_TYPE, ITP_RESOURCE_TYPE,
        UTC_RESOURCE_TYPE, UTI_RESOURCE_TYPE,
    },
    item_uti::{
        ITEM_HELMET_PALETTE_ID, ItemPaletteEntryV1, ItemUtiBuildRequestV1, ItemUtiPropertiesV1,
        read_item_uti_v1, write_item_palette_itp_v1, write_item_uti_v1,
    },
};
use serde_json::json;
use sha2::{Digest, Sha256};

const SOURCE_MODULE_SHA256: &str =
    "4dcf3dd2150a959e58f9a8094008bb604eab5cd095d2753d57c0705128f3be0c";
const HAK_SHA256: &str = "d6f34a55f1d845aa86fe35cdec4df3cd7c0e9494daf26bb8b028307abfbd84ed";
const MODEL_SHA256: &str = "578c5fb940469ff31cf4aae9a50c02e497e7e92dca7c4d33328fb0c7e7f535be";
const MODULE_RESREF: &str = "m2assmpal221";
const MODULE_FILE_NAME: &str = "m2assmpal221.mod";
const MODULE_DISPLAY_NAME: &str = "Meshy2Aurora Sandstorm Mask Palette 221";
const AREA_RESREF: &str = "m2assmarea221";
const AREA_DISPLAY_NAME: &str = "Sandstorm Mask Item Palette 221";
const HAK_RESREF: &str = "m2assmh221";
const UTI_RESREF: &str = "m2assmaskpal221";
const ITP_RESREF: &str = "itempalcus";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let root = env::var("M2A_REPO_ROOT")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| std::path::PathBuf::from(r"C:\Projects\meshy2aurora"));
    let source_root = root.join("proof-output/tlc-sandstorm-mask-helmet-221-v1-20260904");
    let output_root = env::var("M2A_ITEM_PALETTE_OUTPUT")
        .map(std::path::PathBuf::from)
        .unwrap_or_else(|_| {
            root.join("proof-output/tlc-sandstorm-mask-helmet-palette-only-221-v1-20260904")
        });
    if output_root.exists() {
        return Err(format!("immutable output already exists: {}", output_root.display()).into());
    }

    let source_module =
        read_exact_hash(&source_root.join("m2assmmod221.mod"), SOURCE_MODULE_SHA256)?;
    let hak_path = source_root.join("m2assmh221.hak");
    let hak = read_exact_hash(&hak_path, HAK_SHA256)?;
    let hak_archive = ErfArchive::parse(&hak)?;
    let model = hak_archive.find("helm_221", 2002)?;
    if sha256_hex(model) != MODEL_SHA256 {
        return Err("frozen HAK no longer contains the exact helmet model".into());
    }

    let recipe_bytes = fs::read(source_root.join("recipe.json"))?;
    let mut recipe: ItemAppearanceRecipeV1 = serde_json::from_slice(&recipe_bytes)?;
    recipe.identity.uti_resref = UTI_RESREF.to_owned();
    recipe.identity.tag = "M2A_SSMASK_P221".to_owned();
    let uti = write_item_uti_v1(
        &ItemUtiBuildRequestV1 {
            schema_version: 1,
            recipe: recipe.clone(),
            properties: ItemUtiPropertiesV1 {
                description: "Sztywna brązowa maska z krótkim czarnym kapturem.".to_owned(),
                identified_description: "Maska burzy piaskowej przygotowana przez Meshy2Aurora."
                    .to_owned(),
                cost: 1,
                palette_id: ITEM_HELMET_PALETTE_ID,
                comment: "Palette-only Sandstorm Mask helmet 221.".to_owned(),
                ..ItemUtiPropertiesV1::default()
            },
        },
        &GffWriterOptionsV1::default(),
    )?;
    let palette = write_item_palette_itp_v1(&ItemPaletteEntryV1 {
        uti_resref: UTI_RESREF.to_owned(),
        display_name: recipe.identity.display_name.clone(),
        palette_id: ITEM_HELMET_PALETTE_ID,
    })?;

    let source_archive = ErfArchive::parse(&source_module)?;
    let mut module_resources = Vec::new();
    for descriptor in source_archive.resources() {
        if matches!(
            descriptor.resource_type,
            UTI_RESOURCE_TYPE | UTC_RESOURCE_TYPE | ITP_RESOURCE_TYPE
        ) {
            continue;
        }
        let mut payload = source_archive
            .find(&descriptor.resref, descriptor.resource_type)?
            .to_vec();
        match descriptor.resource_type {
            IFO_RESOURCE_TYPE => {
                let mut document = read_expected_gff(&payload, GffFileTypeV1::Ifo)?;
                replace_string(&mut document.root, "Mod_Tag", MODULE_RESREF)?;
                replace_loc_string(&mut document.root, "Mod_Name", MODULE_DISPLAY_NAME)?;
                replace_loc_string(
                    &mut document.root,
                    "Mod_Description",
                    "Palette-only Item module generated by Meshy2Aurora. Contains no creatures.",
                )?;
                payload = write_gff_v32(&document, &GffWriterOptionsV1::default())?.payload;
            }
            2012 => {
                let mut document = read_expected_gff(&payload, GffFileTypeV1::Are)?;
                replace_loc_string(&mut document.root, "Name", AREA_DISPLAY_NAME)?;
                payload = write_gff_v32(&document, &GffWriterOptionsV1::default())?.payload;
            }
            GIT_RESOURCE_TYPE => {
                let mut document = read_expected_gff(&payload, GffFileTypeV1::Git)?;
                empty_creature_list(&mut document.root)?;
                payload = write_gff_v32(&document, &GffWriterOptionsV1::default())?.payload;
            }
            GIC_RESOURCE_TYPE => {
                let mut document = read_expected_gff(&payload, GffFileTypeV1::Gic)?;
                empty_creature_list(&mut document.root)?;
                payload = write_gff_v32(&document, &GffWriterOptionsV1::default())?.payload;
            }
            _ => {}
        }
        module_resources.push(HakResourceInputV1 {
            resref: descriptor.resref.clone(),
            resource_type: descriptor.resource_type,
            payload,
        });
    }
    module_resources.extend([
        HakResourceInputV1 {
            resref: UTI_RESREF.to_owned(),
            resource_type: UTI_RESOURCE_TYPE,
            payload: uti.payload.clone(),
        },
        HakResourceInputV1 {
            resref: ITP_RESREF.to_owned(),
            resource_type: ITP_RESOURCE_TYPE,
            payload: palette.payload.clone(),
        },
    ]);
    let module = write_erf_archive_v1(
        ErfFileType::Module,
        &module_resources,
        &HakWriterOptionsV1::default(),
    )?;
    validate_module(&module.payload, &uti.payload, &palette.payload)?;

    let recipe_json = serde_json::to_vec_pretty(&recipe)?;
    let manifest = serde_json::to_vec_pretty(&json!({
        "schemaVersion": 1,
        "status": "ready_for_owner_palette_check",
        "moduleFilename": MODULE_FILE_NAME,
        "moduleResref": MODULE_RESREF,
        "moduleDisplayName": MODULE_DISPLAY_NAME,
        "areaResref": AREA_RESREF,
        "areaName": AREA_DISPLAY_NAME,
        "orderedHakResrefs": [HAK_RESREF],
        "hakPath": hak_path.to_string_lossy(),
        "hakSha256": HAK_SHA256,
        "modelResref": "helm_221",
        "modelSha256": MODEL_SHA256,
        "utiResref": UTI_RESREF,
        "utiSha256": sha256_hex(&uti.payload),
        "paletteResref": ITP_RESREF,
        "paletteResourceType": ITP_RESOURCE_TYPE,
        "paletteSha256": sha256_hex(&palette.payload),
        "palettePath": "Custom/Armor/Helmets",
        "paletteId": ITEM_HELMET_PALETTE_ID,
        "moduleSha256": sha256_hex(&module.payload),
        "moduleResourceCount": module_resources.len(),
        "creatureResourceCount": 0,
        "placedCreatureCount": 0,
        "sourceModuleSha256": SOURCE_MODULE_SHA256,
        "modelVisibility": "not_tested",
        "proofCompleteness": "missing"
    }))?;

    fs::create_dir_all(&output_root)?;
    write_new(&output_root.join(MODULE_FILE_NAME), &module.payload)?;
    write_new(&output_root.join(format!("{UTI_RESREF}.uti")), &uti.payload)?;
    write_new(&output_root.join("itempalcus.itp"), &palette.payload)?;
    write_new(&output_root.join("recipe.json"), &recipe_json)?;
    write_new(&output_root.join("manifest.json"), &manifest)?;
    println!("{}", String::from_utf8(manifest)?);
    Ok(())
}

fn validate_module(
    bytes: &[u8],
    expected_uti: &[u8],
    expected_palette: &[u8],
) -> Result<(), Box<dyn std::error::Error>> {
    let module = ErfArchive::parse(bytes)?;
    if module.file_type() != ErfFileType::Module || module.resources().len() != 7 {
        return Err("palette-only MOD type or exact resource count differs".into());
    }
    if module
        .resources()
        .iter()
        .any(|resource| resource.resource_type == UTC_RESOURCE_TYPE)
    {
        return Err("palette-only MOD contains a forbidden UTC resource".into());
    }
    if module.find(UTI_RESREF, UTI_RESOURCE_TYPE)? != expected_uti
        || module.find(ITP_RESREF, ITP_RESOURCE_TYPE)? != expected_palette
    {
        return Err("UTI or custom palette differs after MOD readback".into());
    }
    let uti = read_item_uti_v1(
        expected_uti,
        m2a_core::item::ItemCompositionProfileV1::ModelType1,
        &Default::default(),
    )?;
    if uti.identity.uti_resref != UTI_RESREF
        || uti.properties.palette_id != ITEM_HELMET_PALETTE_ID
        || uti.parts.len() != 1
        || uti.parts[0].variant != 221
    {
        return Err("palette UTI does not bind exact helmet variant 221".into());
    }
    for resource_type in [GIT_RESOURCE_TYPE, GIC_RESOURCE_TYPE] {
        let descriptor = module
            .resources()
            .iter()
            .find(|resource| resource.resource_type == resource_type)
            .ok_or("palette-only MOD is missing GIT or GIC")?;
        let document = read_gff_v32(
            module.find(&descriptor.resref, resource_type)?,
            &Default::default(),
        )?;
        let creatures = field_value(&document.root, "Creature List")
            .and_then(|value| match value {
                GffValueV1::List(items) => Some(items),
                _ => None,
            })
            .ok_or("Creature List is missing or has the wrong type")?;
        if !creatures.is_empty() {
            return Err("palette-only MOD contains a placed creature".into());
        }
    }
    let ifo = read_gff_v32(
        module.find("module", IFO_RESOURCE_TYPE)?,
        &Default::default(),
    )?;
    if field_value(&ifo.root, "Mod_Tag")
        != Some(&GffValueV1::String(MODULE_RESREF.as_bytes().to_vec()))
    {
        return Err("module IFO tag differs after readback".into());
    }
    Ok(())
}

fn read_expected_gff(
    bytes: &[u8],
    expected: GffFileTypeV1,
) -> Result<GffDocumentV1, Box<dyn std::error::Error>> {
    let document = read_gff_v32(bytes, &Default::default())?;
    if document.file_type != expected {
        return Err("module fixture GFF type differs".into());
    }
    Ok(document)
}

fn field_value<'a>(structure: &'a GffStructV1, label: &str) -> Option<&'a GffValueV1> {
    structure
        .fields
        .iter()
        .find(|field| field.label == label)
        .map(|field| &field.value)
}

fn field_value_mut<'a>(
    structure: &'a mut GffStructV1,
    label: &str,
) -> Result<&'a mut GffValueV1, Box<dyn std::error::Error>> {
    structure
        .fields
        .iter_mut()
        .find(|field| field.label == label)
        .map(|field| &mut field.value)
        .ok_or_else(|| format!("missing required GFF field {label}").into())
}

fn replace_string(
    structure: &mut GffStructV1,
    label: &str,
    value: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let target = field_value_mut(structure, label)?;
    if !matches!(target, GffValueV1::String(_)) {
        return Err(format!("GFF field {label} is not a CExoString").into());
    }
    *target = GffValueV1::String(value.as_bytes().to_vec());
    Ok(())
}

fn replace_loc_string(
    structure: &mut GffStructV1,
    label: &str,
    value: &str,
) -> Result<(), Box<dyn std::error::Error>> {
    let target = field_value_mut(structure, label)?;
    if !matches!(target, GffValueV1::LocString(_)) {
        return Err(format!("GFF field {label} is not a CExoLocString").into());
    }
    *target = GffValueV1::LocString(GffLocStringV1 {
        string_ref: u32::MAX,
        substrings: vec![GffLocSubstringV1 {
            string_id: 0,
            bytes: value.as_bytes().to_vec(),
        }],
    });
    Ok(())
}

fn empty_creature_list(structure: &mut GffStructV1) -> Result<(), Box<dyn std::error::Error>> {
    let target = field_value_mut(structure, "Creature List")?;
    if !matches!(target, GffValueV1::List(_)) {
        return Err("Creature List is not a GFF List".into());
    }
    *target = GffValueV1::List(Vec::new());
    Ok(())
}

fn read_exact_hash(path: &Path, expected: &str) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let bytes = fs::read(path)?;
    let actual = sha256_hex(&bytes);
    if actual != expected {
        return Err(format!(
            "source hash mismatch for {}: expected {expected}, read {actual}",
            path.display()
        )
        .into());
    }
    Ok(bytes)
}

fn write_new(path: &Path, bytes: &[u8]) -> Result<(), Box<dyn std::error::Error>> {
    let mut file = fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)?;
    file.write_all(bytes)?;
    file.sync_all()?;
    Ok(())
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}
